id: c0c201c70b8341159b6a67296eeb56b4
initial_creation_type: ocr
source_metadata:
  volumes:
    55c6d62275f34dd89ff0b924dee639ad:
      base_file: v063.txt
      image_group_id: I1PD95909
      title: ''
      total_pages: 1902
      volume_number: 64
